### ISSUE TITLE
Банк2 в выгрузках Альфабанк и СберБанк

### ISSUE THREAD

**Issue by politsin** [kilylabs/client-bank-exchange-php#1]
Поля `ПлательщикБанк2` и `ПолучательБанк2`  отсутсвуют в
выгрузках сбербанка(ВерсияФормата=1.02) и альфабанка (ВерсияФормата=1.01).

При попытке обратиться получаем ексепшен.

**Comment by ab-kily** [comment]
Спасибо! Когда-то я уже это поправил, но если ошибка присутствует по-прежнему, откройте issue заново. Хотя я думаю, вряд-ли вы это сделаете, спустя 6 лет после создания этой задачи 😂😂😂

**Comment by politsin** [comment]
спасибо =)
