### ISSUE TITLE
Переход на PHP 8

### ISSUE THREAD

**Issue by Positic** [kilylabs/client-bank-exchange-php#11]
Можно как-то исправить это?

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Parser::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Parser.php on line 139

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Parser::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Parser.php on line 149

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Parser::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Parser.php on line 130

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Parser::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Parser.php on line 144

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Component::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Component.php on line 97

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Component::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Component.php on line 107

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Component::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Component.php on line 88

Deprecated: Return type of Kily\Tools1C\ClientBankExchange\Component::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/www/sites/klx/docs/server/php/vendor/kilylabs/client-bank-exchange-php/src/ClientBankExchange/Component.php on line 102

**Comment by ab-kily** [comment]
Привет и спасибо за сообщение! Да, давно пора, постараюсь сегодня сделать новый релиз с исправлением.
