### ISSUE TITLE
DocumentSection НазначениеПлатежа exception

### ISSUE THREAD

**Issue by kozhevnikovpe** [kilylabs/client-bank-exchange-php#3]
Поля
            'НазначениеПлатежа 1',
            'НазначениеПлатежа 2',
            'НазначениеПлатежа 3',
            'НазначениеПлатежа 4',
            'НазначениеПлатежа 5',
            'НазначениеПлатежа 6',

должны быть без пробела

**Comment by ab-kily** [comment]
Спасибо за сообщение! Исправлено.
