### ISSUE TITLE
Определение кодировки

### ISSUE THREAD

**Issue by arthurshlain** [kilylabs/client-bank-exchange-php#6]
Можно добавить в состав парсера определение кодировки.

```
$data = file_get_contents($filename);
$enc = mb_detect_encoding($data, mb_list_encodings(), true);
```

Правда к минимальным требованиям добавится расширение mbstring.

P.S. Поставил звезду, спасибо!

**Comment by ab-kily** [comment]
Cпасибо за предложение! Данная функциональность потребует включения расширения mbstring в качестве зависимости, чего не очень то хотелось... Если предложите другое решение (а еще лучше пул-реквест 😌), то постараюсь включить эту фитчу.
