### ISSUE TITLE
Несколько блоков СекцияРасчСчет

### ISSUE THREAD

**Issue by arthurshlain** [kilylabs/client-bank-exchange-php#8]
Если выгрузка не регулярная, банк может отдать несколько блоков `СекцияРасчСчет`.
Сейчас в `remainings` выводятся только данные первого блока.

Кому то может быть больше интересен `КонечныйОстаток` по последнему блоку.

**Comment by platro** [comment]
Я считаю это исправление было неверным. Раньше remainigs являлся МАССИВОМ всех блоков из выгрузки (на каждый день начальный и конечный остаток), а не только первый блок. И это было более правильно, так как можно было получить начальный остаток на первый день выгрузки. А сейчас получаю начальный остаток только на последний день выгрузки.
